from datetime import date as date_type
from datetime import datetime, time
from decimal import Decimal
from enum import StrEnum
from typing import Any

from sqlalchemy import (
    CheckConstraint,
    Computed,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    Time,
    text,
)
from sqlalchemy.dialects.postgresql import TSRANGE, ExcludeConstraint
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database.base import Base
from app.core.database.mixins import IdIntPk, TimestampMixin


class BookingKind(StrEnum):
    TABLE_RESERVATION = "table_reservation"
    HALL_EVENT = "hall_event"


class BookingStatus(StrEnum):
    PENDING = "pending"
    CONFIRMED = "confirmed"
    CHECKED_IN = "checked_in"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    NO_SHOW = "no_show"
    EXPIRED = "expired"


class Booking(IdIntPk, TimestampMixin, Base):
    """One table, two kinds — restaurant reservations and to'yxona hall events.

    They share roughly 80% of their columns; splitting them would duplicate the
    ticket, QR, deposit, payment and cancellation machinery twice.

    `booking_date` + `start_time` are local venue values with no UTC conversion:
    11:00 must stay 11:00. UTC applies only to audit columns. `reserved_range` is
    therefore TSRANGE, not TSTZRANGE — a tz-aware range would contradict that.

    Double booking is settled in Postgres, not Python: two users tapping
    "Tasdiqlash va band qilish" in the same second produce one success and one
    integrity error. The partial unique index below is autogenerated from this
    declaration; the exclusion constraint is written by hand in the migration,
    because Alembic does not render `ExcludeConstraint`.
    """

    __tablename__ = "bookings"
    __table_args__ = (
        # One booking per table per time window. Needs btree_gist, because it mixes
        # `=` on an integer with `&&` on a range in one GiST index.
        ExcludeConstraint(
            ("table_id", "="),
            ("reserved_range", "&&"),
            name="no_overlapping_table_bookings",
            using="gist",
            where=text("status IN ('pending', 'confirmed', 'checked_in')"),
        ),
        # One hall event per venue per day.
        Index(
            "one_hall_event_per_day",
            "venue_id",
            "booking_date",
            unique=True,
            postgresql_where=text(
                "kind = 'hall_event' AND status IN ('pending', 'confirmed', 'checked_in')"
            ),
        ),
        Index("ix_bookings_venue_id_booking_date_status", "venue_id", "booking_date", "status"),
        CheckConstraint("kind IN ('table_reservation', 'hall_event')", name="ck_bookings_kind"),
        CheckConstraint(
            "status IN ('pending', 'confirmed', 'checked_in', 'completed',"
            " 'cancelled', 'no_show', 'expired')",
            name="ck_bookings_status",
        ),
        CheckConstraint(
            "kind <> 'table_reservation' OR (table_id IS NOT NULL AND guest_tier_id IS NULL)",
            name="ck_bookings_table_reservation_shape",
        ),
        CheckConstraint(
            "kind <> 'hall_event' OR (guest_tier_id IS NOT NULL AND table_id IS NULL)",
            name="ck_bookings_hall_event_shape",
        ),
    )

    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), nullable=False, index=True)
    venue_id: Mapped[int] = mapped_column(ForeignKey("venues.id"), nullable=False)
    kind: Mapped[str] = mapped_column(String(20), nullable=False)
    booking_date: Mapped[date_type] = mapped_column(Date, nullable=False)
    start_time: Mapped[time] = mapped_column(Time, nullable=False)
    end_time: Mapped[time] = mapped_column(Time, nullable=False)
    guests_count: Mapped[int] = mapped_column(Integer, nullable=False)
    status: Mapped[str] = mapped_column(String(20), default=BookingStatus.PENDING, nullable=False)
    contact_name: Mapped[str] = mapped_column(String(200), nullable=False)
    contact_phone: Mapped[str] = mapped_column(String(20), nullable=False)
    note: Mapped[str | None] = mapped_column(Text, nullable=True)

    subtotal: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0, nullable=False)
    discount_amount: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0, nullable=False)
    deposit_amount: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0, nullable=False)
    deposit_paid_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=False), nullable=True
    )
    total_amount: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0, nullable=False)
    currency: Mapped[str] = mapped_column(String(3), default="UZS", nullable=False)
    promo_code_id: Mapped[int | None] = mapped_column(
        ForeignKey("promo_codes.id", ondelete="SET NULL"), nullable=True
    )

    receipt_number: Mapped[str] = mapped_column(String(50), unique=True, nullable=False)
    ticket_code: Mapped[str] = mapped_column(String(16), unique=True, nullable=False)
    qr_token: Mapped[str] = mapped_column(String(32), unique=True, nullable=False)

    auto_cancel_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=False), nullable=True)
    confirmed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=False), nullable=True)
    checked_in_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=False), nullable=True)
    checked_out_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=False), nullable=True)
    seated_minutes: Mapped[int | None] = mapped_column(Integer, nullable=True)
    cancelled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=False), nullable=True)
    cancel_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=False), nullable=True)

    # table_reservation only
    table_id: Mapped[int | None] = mapped_column(ForeignKey("venue_tables.id"), nullable=True)
    reserved_range: Mapped[Any] = mapped_column(
        TSRANGE,
        Computed(
            "tsrange((booking_date + start_time), (booking_date + end_time))",
            persisted=True,
        ),
        nullable=True,
    )

    # hall_event only
    guest_tier_id: Mapped[int | None] = mapped_column(
        ForeignKey("venue_guest_tiers.id"), nullable=True
    )
    venue_service_id: Mapped[int | None] = mapped_column(
        ForeignKey("venue_services.id"), nullable=True
    )
