"""orders

Revision ID: 92a334e4ceea
Revises: ace0856d75f4
Create Date: 2026-07-30 10:06:15.870926

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "92a334e4ceea"
down_revision: str | Sequence[str] | None = "ace0856d75f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=True),
        sa.Column("booking_id", sa.Integer(), nullable=True),
        sa.Column("order_number", sa.Integer(), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("guests_count", sa.SmallInteger(), nullable=True),
        sa.Column("waiter_staff_id", sa.Integer(), nullable=True),
        sa.Column("opened_by_staff_id", sa.Integer(), nullable=False),
        sa.Column("closed_by_staff_id", sa.Integer(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("service_charge", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('dine_in', 'takeaway')", name="ck_orders_kind"),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'served', 'awaiting_payment', 'completed', 'cancelled')",
            name="ck_orders_status",
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(["closed_by_staff_id"], ["venue_staff.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["opened_by_staff_id"],
            ["venue_staff.id"],
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["venue_tables.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.ForeignKeyConstraint(["waiter_staff_id"], ["venue_staff.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue_id", "business_date", "order_number"),
    )
    op.create_index(
        "ix_orders_venue_id_business_date", "orders", ["venue_id", "business_date"], unique=False
    )
    op.create_index(
        "ix_orders_venue_id_status_opened_at",
        "orders",
        ["venue_id", "status", "opened_at"],
        unique=False,
    )
    op.create_index(
        "one_open_order_per_table",
        "orders",
        ["table_id"],
        unique=True,
        postgresql_where=sa.text(
            "table_id IS NOT NULL AND status NOT IN ('completed', 'cancelled')"
        ),
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("name_snapshot", sa.String(length=255), nullable=False),
        sa.Column("variant_name_snapshot", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("added_by_staff_id", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column("served_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('new', 'sent_to_kitchen', 'cooking', 'ready', 'served', 'cancelled')",
            name="ck_order_items_status",
        ),
        sa.ForeignKeyConstraint(
            ["added_by_staff_id"],
            ["venue_staff.id"],
        ),
        sa.ForeignKeyConstraint(
            ["menu_item_id"],
            ["menu_items.id"],
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["menu_item_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_order_items_order_id_status", "order_items", ["order_id", "status"], unique=False
    )
    op.create_table(
        "order_payments",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("received_by_staff_id", sa.Integer(), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=False),
        sa.Column("provider_transaction_id", sa.String(length=255), nullable=True),
        sa.Column("change_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method IN ('cash', 'card', 'transfer', 'click', 'payme', 'other')",
            name="ck_order_payments_method",
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["received_by_staff_id"],
            ["venue_staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_payments_order_id"), "order_payments", ["order_id"], unique=False
    )
    op.create_table(
        "order_status_history",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("changed_by_staff_id", sa.Integer(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["changed_by_staff_id"], ["venue_staff.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_status_history_order_id"), "order_status_history", ["order_id"], unique=False
    )
    op.create_table(
        "receipts",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("receipt_number", sa.String(length=50), nullable=False),
        sa.Column("printed_at", sa.DateTime(), nullable=False),
        sa.Column("printed_by_staff_id", sa.Integer(), nullable=False),
        sa.Column("fiscal_sign", sa.String(length=255), nullable=True),
        sa.Column("fiscal_serial", sa.String(length=255), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reprinted_count", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["printed_by_staff_id"],
            ["venue_staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
        sa.UniqueConstraint("receipt_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("receipts")
    op.drop_index(op.f("ix_order_status_history_order_id"), table_name="order_status_history")
    op.drop_table("order_status_history")
    op.drop_index(op.f("ix_order_payments_order_id"), table_name="order_payments")
    op.drop_table("order_payments")
    op.drop_index("ix_order_items_order_id_status", table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(
        "one_open_order_per_table",
        table_name="orders",
        postgresql_where=sa.text(
            "table_id IS NOT NULL AND status NOT IN ('completed', 'cancelled')"
        ),
    )
    op.drop_index("ix_orders_venue_id_status_opened_at", table_name="orders")
    op.drop_index("ix_orders_venue_id_business_date", table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
