"""drop auth identities

Revision ID: ab4757664a2b
Revises: a7e3f0c94b21
Create Date: 2026-08-10 17:52:45.115914

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ab4757664a2b"
down_revision: str | Sequence[str] | None = "a7e3f0c94b21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_identities_user_id"), table_name="auth_identities")
    op.drop_table("auth_identities")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Recreates the empty table and its constraints only. The rows dropped by
    `upgrade()` are gone for good — this cannot restore them.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_identities",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("provider", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("provider_user_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("provider_email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "raw_profile",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("timezone('UTC'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("timezone('UTC'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider::text = 'google'::text", name=op.f("ck_auth_identities_provider")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("auth_identities_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("auth_identities_pkey")),
        sa.UniqueConstraint(
            "provider",
            "provider_user_id",
            name=op.f("auth_identities_provider_provider_user_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_auth_identities_user_id"), "auth_identities", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
