"""staff

Revision ID: dc785e579344
Revises: ca4b9b7a5336
Create Date: 2026-07-30 10:06:07.999797

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc785e579344"
down_revision: str | Sequence[str] | None = "ca4b9b7a5336"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("group", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "staff_roles",
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("scope", sa.String(length=10), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.CheckConstraint("scope IN ('group', 'venue')", name="ck_staff_roles_scope"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "scope", name="uq_staff_roles_id_scope"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "staff_role_permissions",
        sa.Column("staff_role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["staff_role_id"], ["staff_roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("staff_role_id", "permission_id"),
    )
    op.create_table(
        "staff_role_translations",
        sa.Column("staff_role_id", sa.Integer(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.ForeignKeyConstraint(["staff_role_id"], ["staff_roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("staff_role_id", "language_id"),
    )
    op.create_table(
        "staff_invitations",
        sa.Column("venue_group_id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("staff_role_id", sa.Integer(), nullable=False),
        sa.Column("temp_password_hash", sa.String(length=255), nullable=False),
        sa.Column("sms_sent_at", sa.DateTime(), nullable=True),
        sa.Column("sms_provider_id", sa.String(length=255), nullable=True),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["staff_role_id"],
            ["staff_roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_group_id"],
            ["venue_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_staff_invitations_phone_expires_at",
        "staff_invitations",
        ["phone", "expires_at"],
        unique=False,
    )
    op.create_table(
        "venue_staff",
        sa.Column("venue_group_id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("staff_role_id", sa.Integer(), nullable=False),
        sa.Column("role_scope", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("invited_by_user_id", sa.Integer(), nullable=True),
        sa.Column("invited_at", sa.DateTime(), nullable=False),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role_scope <> 'venue' OR venue_id IS NOT NULL",
            name="ck_venue_staff_venue_scope_requires_venue",
        ),
        sa.CheckConstraint("role_scope IN ('group', 'venue')", name="ck_venue_staff_role_scope"),
        sa.ForeignKeyConstraint(["invited_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["staff_role_id", "role_scope"],
            ["staff_roles.id", "staff_roles.scope"],
            name="fk_venue_staff_role_scope",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_group_id"],
            ["venue_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue_id", "user_id"),
    )
    op.create_index(op.f("ix_venue_staff_user_id"), "venue_staff", ["user_id"], unique=False)
    op.create_index(
        "ix_venue_staff_venue_group_id_is_active",
        "venue_staff",
        ["venue_group_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_venue_staff_venue_id_staff_role_id",
        "venue_staff",
        ["venue_id", "staff_role_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_venue_staff_venue_id_staff_role_id", table_name="venue_staff")
    op.drop_index("ix_venue_staff_venue_group_id_is_active", table_name="venue_staff")
    op.drop_index(op.f("ix_venue_staff_user_id"), table_name="venue_staff")
    op.drop_table("venue_staff")
    op.drop_index("ix_staff_invitations_phone_expires_at", table_name="staff_invitations")
    op.drop_table("staff_invitations")
    op.drop_table("staff_role_translations")
    op.drop_table("staff_role_permissions")
    op.drop_table("staff_roles")
    op.drop_table("permissions")
    # ### end Alembic commands ###
