"""venue type enum

Revision ID: 6ee3f460f08b
Revises: ab4757664a2b
Create Date: 2026-08-10 18:08:31.922768

Hand-written, not autogenerated. Autogenerate emits the add-column and the
drop-table with nothing in between, which discards every venue's type: the only
record of it lives in `venue_venue_types` until the backfill has copied it out.

The order here is load-bearing — add nullable -> backfill from the join table ->
fold the values that no longer exist -> tighten to NOT NULL and constrain -> and
only then drop what was read from.

Three foreign keys pointed at `venue_types`, not two: `venue_groups`,
`venue_venue_types`, and `service_catalog.applies_to_venue_type_id`. The last one
would have made `DROP TABLE venue_types` fail outright, so it moves to a slug
column of its own here rather than being left dangling.

Venue counts by type before this ran, in development: kafe 0, restoran 2,
toyxona 2; one venue group, primary type toyxona. The `kafe` fold therefore
rewrote nothing there, but it is kept because production may differ.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ee3f460f08b"
down_revision: str | Sequence[str] | None = "ab4757664a2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The two survivors, with the sort order the picker used to read off the table.
SURVIVING_TYPES = [("restoran", "Restoran", 1), ("toyxona", "To'yxona", 2)]


def upgrade() -> None:
    # 1. Nullable for now: there is nothing to put in these until the backfill runs.
    op.add_column("venues", sa.Column("venue_type", sa.String(length=20), nullable=True))
    op.add_column(
        "venue_groups",
        sa.Column("primary_venue_type", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "service_catalog",
        sa.Column("applies_to_venue_type", sa.String(length=20), nullable=True),
    )

    # 2. A venue with several types takes its lowest-sorted one, so `restoran`
    #    wins over `toyxona` and both win over `kafe`.
    op.execute("""
        UPDATE venues v SET venue_type = sub.slug
        FROM (
            SELECT DISTINCT ON (vvt.venue_id) vvt.venue_id, vt.slug
            FROM venue_venue_types vvt
            JOIN venue_types vt ON vt.id = vvt.venue_type_id
            ORDER BY vvt.venue_id, vt.sort_order
        ) AS sub
        WHERE sub.venue_id = v.id
    """)
    op.execute("""
        UPDATE venue_groups g SET primary_venue_type = vt.slug
        FROM venue_types vt
        WHERE vt.id = g.primary_venue_type_id
    """)
    op.execute("""
        UPDATE service_catalog sc SET applies_to_venue_type = vt.slug
        FROM venue_types vt
        WHERE vt.id = sc.applies_to_venue_type_id
    """)

    # 3. `kafe` is not a value any more, and neither is a venue with no type row.
    op.execute(
        "UPDATE venues SET venue_type = 'restoran' WHERE venue_type IS DISTINCT FROM 'toyxona'"
    )
    op.execute(
        "UPDATE venue_groups SET primary_venue_type = 'restoran' "
        "WHERE primary_venue_type IS DISTINCT FROM 'toyxona'"
    )
    # `service_catalog` keeps its NULLs: there, NULL means "suits any venue", which
    # is a real value rather than a missing one, so only `kafe` is folded.
    op.execute(
        "UPDATE service_catalog SET applies_to_venue_type = 'restoran' "
        "WHERE applies_to_venue_type IS NOT NULL AND applies_to_venue_type <> 'toyxona'"
    )

    # 4. Now every row has a value, so the constraints can go on.
    op.alter_column("venues", "venue_type", existing_type=sa.String(length=20), nullable=False)
    op.alter_column(
        "venue_groups", "primary_venue_type", existing_type=sa.String(length=20), nullable=False
    )
    op.create_check_constraint(
        "ck_venues_venue_type", "venues", "venue_type IN ('restoran', 'toyxona')"
    )
    op.create_check_constraint(
        "ck_venue_groups_primary_venue_type",
        "venue_groups",
        "primary_venue_type IN ('restoran', 'toyxona')",
    )
    op.create_check_constraint(
        "ck_service_catalog_applies_to_venue_type",
        "service_catalog",
        "applies_to_venue_type IS NULL OR applies_to_venue_type IN ('restoran', 'toyxona')",
    )
    op.create_index("ix_venues_venue_type", "venues", ["venue_type"])

    # 5. Only now is it safe to drop what we read from. Dropping the two foreign-key
    #    columns first is what makes `venue_types` droppable at all.
    op.drop_column("service_catalog", "applies_to_venue_type_id")
    op.drop_column("venue_groups", "primary_venue_type_id")
    op.drop_table("venue_venue_types")
    # `venue_type_translations` is not dropped here: 73548a20054d already folded it
    # into `venue_types.name` and dropped the table.
    op.drop_table("venue_types")


def downgrade() -> None:
    """Rebuild the lookup table and the join, and point the two keys back at it.

    Lossy in one direction: `kafe` cannot be resurrected. Its row is recreated by
    the seed revision, not by this one, and the venues that carried it were folded
    into `restoran` by `upgrade` with no record of which ones they were. A venue
    that was both `restoran` and `toyxona` comes back with one type, for the same
    reason.
    """
    op.create_table(
        "venue_types",
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("icon_url", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        # `name` was added by 73548a20054d when the translation tables were folded in.
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    for slug, name, sort_order in SURVIVING_TYPES:
        quoted_name = name.replace("'", "''")  # To'yxona
        op.execute(
            "INSERT INTO venue_types (slug, name, sort_order, is_active) "
            f"VALUES ('{slug}', '{quoted_name}', {sort_order}, true)"
        )

    op.create_table(
        "venue_venue_types",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("venue_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["venue_type_id"], ["venue_types.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("venue_id", "venue_type_id"),
    )
    op.execute("""
        INSERT INTO venue_venue_types (venue_id, venue_type_id)
        SELECT v.id, vt.id FROM venues v JOIN venue_types vt ON vt.slug = v.venue_type
    """)

    # Nullable, backfill, tighten — the same order as `upgrade`, for the same reason.
    op.add_column("venue_groups", sa.Column("primary_venue_type_id", sa.Integer(), nullable=True))
    op.execute("""
        UPDATE venue_groups g SET primary_venue_type_id = vt.id
        FROM venue_types vt WHERE vt.slug = g.primary_venue_type
    """)
    op.alter_column(
        "venue_groups", "primary_venue_type_id", existing_type=sa.Integer(), nullable=False
    )
    op.create_foreign_key(None, "venue_groups", "venue_types", ["primary_venue_type_id"], ["id"])

    op.add_column(
        "service_catalog", sa.Column("applies_to_venue_type_id", sa.Integer(), nullable=True)
    )
    op.execute("""
        UPDATE service_catalog sc SET applies_to_venue_type_id = vt.id
        FROM venue_types vt WHERE vt.slug = sc.applies_to_venue_type
    """)
    op.create_foreign_key(
        None,
        "service_catalog",
        "venue_types",
        ["applies_to_venue_type_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # Postgres drops a single-column CHECK along with its column, so the three
    # `ck_*_venue_type` constraints need no separate statement.
    op.drop_index("ix_venues_venue_type", table_name="venues")
    op.drop_column("service_catalog", "applies_to_venue_type")
    op.drop_column("venue_groups", "primary_venue_type")
    op.drop_column("venues", "venue_type")
