"""venues

Revision ID: ca4b9b7a5336
Revises: 07f629cbd1cc
Create Date: 2026-07-30 10:06:06.656760

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca4b9b7a5336"
down_revision: str | Sequence[str] | None = "07f629cbd1cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "venues",
        sa.Column("venue_group_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("manager_user_id", sa.Integer(), nullable=True),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("street", sa.String(length=255), nullable=False),
        sa.Column("house_number", sa.String(length=50), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("total_seats", sa.Integer(), nullable=True),
        sa.Column("capacity_min", sa.Integer(), nullable=True),
        sa.Column("capacity_max", sa.Integer(), nullable=True),
        sa.Column("base_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("min_advance_booking_days", sa.SmallInteger(), nullable=False),
        sa.Column("late_grace_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("requires_deposit", sa.Boolean(), nullable=False),
        sa.Column("deposit_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rating_avg", sa.Numeric(precision=2, scale=1), nullable=False),
        sa.Column("reviews_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("onboarding_step", sa.SmallInteger(), nullable=False),
        sa.Column("onboarded_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'pending', 'active', 'blocked', 'closed')", name="ck_venues_status"
        ),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
        ),
        sa.ForeignKeyConstraint(["manager_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_group_id"],
            ["venue_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_venues_owner_id"), "venues", ["owner_id"], unique=False)
    op.create_index(
        "ix_venues_venue_group_id_status", "venues", ["venue_group_id", "status"], unique=False
    )
    op.create_table(
        "venue_amenities",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("amenity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["amenity_id"], ["amenities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("venue_id", "amenity_id"),
    )
    op.create_table(
        "venue_guest_tiers",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("min_guests", sa.Integer(), nullable=False),
        sa.Column("max_guests", sa.Integer(), nullable=True),
        sa.Column("base_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_venue_guest_tiers_venue_id"), "venue_guest_tiers", ["venue_id"], unique=False
    )
    op.create_table(
        "venue_photos",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_cover", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_venue_photos_venue_id"), "venue_photos", ["venue_id"], unique=False)
    op.create_table(
        "venue_special_days",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=True),
        sa.Column("closes_at", sa.Time(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_venue_special_days_venue_id"), "venue_special_days", ["venue_id"], unique=False
    )
    op.create_table(
        "venue_translations",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tagline", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue_id", "language_id"),
    )
    op.create_index(
        "ix_venue_translations_name_trgm",
        "venue_translations",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_table(
        "venue_venue_types",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("venue_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["venue_type_id"], ["venue_types.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("venue_id", "venue_type_id"),
    )
    op.create_table(
        "venue_working_hours",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=True),
        sa.Column("closes_at", sa.Time(), nullable=True),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_venue_working_hours_venue_id"), "venue_working_hours", ["venue_id"], unique=False
    )
    op.create_table(
        "venue_zones",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_venue_zones_venue_id"), "venue_zones", ["venue_id"], unique=False)
    op.create_table(
        "venue_tables",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("seats", sa.SmallInteger(), nullable=False),
        sa.Column("zone_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["zone_id"], ["venue_zones.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue_id", "number"),
    )
    op.create_index(op.f("ix_venue_tables_venue_id"), "venue_tables", ["venue_id"], unique=False)
    op.create_table(
        "venue_zone_translations",
        sa.Column("zone_id", sa.Integer(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.ForeignKeyConstraint(["zone_id"], ["venue_zones.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("zone_id", "language_id"),
    )
    op.create_table(
        "venue_table_qrs",
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("printed_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["table_id"], ["venue_tables.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        op.f("ix_venue_table_qrs_table_id"), "venue_table_qrs", ["table_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_venue_table_qrs_table_id"), table_name="venue_table_qrs")
    op.drop_table("venue_table_qrs")
    op.drop_table("venue_zone_translations")
    op.drop_index(op.f("ix_venue_tables_venue_id"), table_name="venue_tables")
    op.drop_table("venue_tables")
    op.drop_index(op.f("ix_venue_zones_venue_id"), table_name="venue_zones")
    op.drop_table("venue_zones")
    op.drop_index(op.f("ix_venue_working_hours_venue_id"), table_name="venue_working_hours")
    op.drop_table("venue_working_hours")
    op.drop_table("venue_venue_types")
    op.drop_index(
        "ix_venue_translations_name_trgm",
        table_name="venue_translations",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("venue_translations")
    op.drop_index(op.f("ix_venue_special_days_venue_id"), table_name="venue_special_days")
    op.drop_table("venue_special_days")
    op.drop_index(op.f("ix_venue_photos_venue_id"), table_name="venue_photos")
    op.drop_table("venue_photos")
    op.drop_index(op.f("ix_venue_guest_tiers_venue_id"), table_name="venue_guest_tiers")
    op.drop_table("venue_guest_tiers")
    op.drop_table("venue_amenities")
    op.drop_index("ix_venues_venue_group_id_status", table_name="venues")
    op.drop_index(op.f("ix_venues_owner_id"), table_name="venues")
    op.drop_table("venues")
    # ### end Alembic commands ###
