"""bookings

Revision ID: ace0856d75f4
Revises: 5fb4398780ae
Create Date: 2026-07-30 10:06:14.521272

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ace0856d75f4"
down_revision: str | Sequence[str] | None = "5fb4398780ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("booking_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("guests_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("contact_name", sa.String(length=200), nullable=False),
        sa.Column("contact_phone", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("deposit_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("deposit_paid_at", sa.DateTime(), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("promo_code_id", sa.Integer(), nullable=True),
        sa.Column("receipt_number", sa.String(length=50), nullable=False),
        sa.Column("ticket_code", sa.String(length=16), nullable=False),
        sa.Column("qr_token", sa.String(length=32), nullable=False),
        sa.Column("auto_cancel_at", sa.DateTime(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("checked_in_at", sa.DateTime(), nullable=True),
        sa.Column("checked_out_at", sa.DateTime(), nullable=True),
        sa.Column("seated_minutes", sa.Integer(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("table_id", sa.Integer(), nullable=True),
        sa.Column(
            "reserved_range",
            postgresql.TSRANGE(),
            sa.Computed(
                "tsrange((booking_date + start_time), (booking_date + end_time))", persisted=True
            ),
            nullable=True,
        ),
        sa.Column("guest_tier_id", sa.Integer(), nullable=True),
        sa.Column("venue_service_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("table_id"), "="),
            (sa.column("reserved_range"), "&&"),
            where=sa.text("status IN ('pending', 'confirmed', 'checked_in')"),
            using="gist",
            name="no_overlapping_table_bookings",
        ),
        sa.CheckConstraint(
            "kind <> 'hall_event' OR (guest_tier_id IS NOT NULL AND table_id IS NULL)",
            name="ck_bookings_hall_event_shape",
        ),
        sa.CheckConstraint(
            "kind <> 'table_reservation' OR (table_id IS NOT NULL AND guest_tier_id IS NULL)",
            name="ck_bookings_table_reservation_shape",
        ),
        sa.CheckConstraint("kind IN ('table_reservation', 'hall_event')", name="ck_bookings_kind"),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed', 'checked_in', 'completed', 'cancelled', 'no_show', 'expired')",
            name="ck_bookings_status",
        ),
        sa.ForeignKeyConstraint(
            ["guest_tier_id"],
            ["venue_guest_tiers.id"],
        ),
        sa.ForeignKeyConstraint(["promo_code_id"], ["promo_codes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["venue_tables.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_service_id"],
            ["venue_services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("qr_token"),
        sa.UniqueConstraint("receipt_number"),
        sa.UniqueConstraint("ticket_code"),
    )
    op.create_index(op.f("ix_bookings_user_id"), "bookings", ["user_id"], unique=False)
    op.create_index(
        "ix_bookings_venue_id_booking_date_status",
        "bookings",
        ["venue_id", "booking_date", "status"],
        unique=False,
    )
    op.create_index(
        "one_hall_event_per_day",
        "bookings",
        ["venue_id", "booking_date"],
        unique=True,
        postgresql_where=sa.text(
            "kind = 'hall_event' AND status IN ('pending', 'confirmed', 'checked_in')"
        ),
    )
    op.create_table(
        "venue_blocked_slots",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("reason", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('manual', 'maintenance', 'private_event')",
            name="ck_venue_blocked_slots_reason",
        ),
        sa.ForeignKeyConstraint(["table_id"], ["venue_tables.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_venue_blocked_slots_venue_id"), "venue_blocked_slots", ["venue_id"], unique=False
    )
    op.create_table(
        "booking_items",
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("name_snapshot", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["menu_item_id"],
            ["menu_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_booking_items_booking_id"), "booking_items", ["booking_id"], unique=False
    )
    op.create_table(
        "booking_price_lines",
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("line_type", sa.String(length=30), nullable=False),
        sa.Column("label_snapshot", sa.String(length=255), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "line_type IN ('hall_rental', 'catering', 'service_logistics', 'discount', 'deposit')",
            name="ck_booking_price_lines_type",
        ),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_booking_price_lines_booking_id"),
        "booking_price_lines",
        ["booking_id"],
        unique=False,
    )
    op.create_table(
        "booking_services",
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("venue_service_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("name_snapshot", sa.String(length=255), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["venue_service_id"],
            ["venue_services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_booking_services_booking_id"), "booking_services", ["booking_id"], unique=False
    )
    op.create_table(
        "booking_status_history",
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("changed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_booking_status_history_booking_id"),
        "booking_status_history",
        ["booking_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.create_foreign_key(
        "promo_code_redemptions_booking_id_fkey",
        "promo_code_redemptions",
        "bookings",
        ["booking_id"],
        ["id"],
    )

    op.create_foreign_key(
        "promo_code_redemptions_subscription_id_fkey",
        "promo_code_redemptions",
        "user_subscriptions",
        ["subscription_id"],
        ["id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "promo_code_redemptions_subscription_id_fkey", "promo_code_redemptions", type_="foreignkey"
    )
    op.drop_constraint(
        "promo_code_redemptions_booking_id_fkey", "promo_code_redemptions", type_="foreignkey"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_booking_status_history_booking_id"), table_name="booking_status_history")
    op.drop_table("booking_status_history")
    op.drop_index(op.f("ix_booking_services_booking_id"), table_name="booking_services")
    op.drop_table("booking_services")
    op.drop_index(op.f("ix_booking_price_lines_booking_id"), table_name="booking_price_lines")
    op.drop_table("booking_price_lines")
    op.drop_index(op.f("ix_booking_items_booking_id"), table_name="booking_items")
    op.drop_table("booking_items")
    op.drop_index(op.f("ix_venue_blocked_slots_venue_id"), table_name="venue_blocked_slots")
    op.drop_table("venue_blocked_slots")
    op.drop_index(
        "one_hall_event_per_day",
        table_name="bookings",
        postgresql_where=sa.text(
            "kind = 'hall_event' AND status IN ('pending', 'confirmed', 'checked_in')"
        ),
    )
    op.drop_index("ix_bookings_venue_id_booking_date_status", table_name="bookings")
    op.drop_index(op.f("ix_bookings_user_id"), table_name="bookings")
    op.drop_table("bookings")
    # ### end Alembic commands ###
