"""sms_messages

Revision ID: 3845cb0ff4f9
Revises: b7834c92fef5
Create Date: 2026-07-30 14:27:17.549267

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3845cb0ff4f9"
down_revision: str | Sequence[str] | None = "b7834c92fef5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_messages",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("template_key", sa.String(length=50), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_request_id", sa.String(length=64), nullable=True),
        sa.Column("provider_message_id", sa.String(length=64), nullable=True),
        sa.Column("parts_count", sa.SmallInteger(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("provider_status_raw", sa.String(length=30), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("status_updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose IN ('otp', 'staff_invitation', 'notification')", name="ck_sms_messages_purpose"
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'sent', 'delivered', 'partly_delivered', 'undelivered', 'expired', 'rejected', 'failed', 'skipped')",
            name="ck_sms_messages_status",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_request_id"),
    )
    op.create_index(
        "ix_sms_messages_phone_created_at", "sms_messages", ["phone", "created_at"], unique=False
    )
    op.create_index(
        "ix_sms_messages_status_created_at", "sms_messages", ["status", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sms_messages_status_created_at", table_name="sms_messages")
    op.drop_index("ix_sms_messages_phone_created_at", table_name="sms_messages")
    op.drop_table("sms_messages")
    # ### end Alembic commands ###
